### ISSUE TITLE
Как запустить на localhost 3000?

### ISSUE THREAD

**Issue by seriiserii825** [dergunovs/nuxt-express#8]
Добрый день. 
Я смотрю различные курсы и там во время установки просят установить express, или другие модули для работы с сервером. 
В текущих версиях такой опции нет. 

Как вы думаете, почему они это сделали?

**Comment by dergunovs** [comment]
Добрый день. Фронтенд - это отдельная часть приложения, которая должна быть минимально связана с бэком.
Тем более, когда разработчики в установщик добавляют другие фреймворки, то они отчасти берут на себя ответственность за совместимость.

Тем не менее, для небольших приложений и сайтов приложение-монолит может быть неплохим выбором.
